---Default Permissions
INSERT INTO permissions (name) VALUES
    ('PERMISSION_CREATE_USER'),
    ('PERMISSION_DELETE_USER'),
    ('PERMISSION_VIEW_USER'),
    ('PERMISSION_UPDATE_USER'),
    ('PERMISSION_CREATE_COURSE'),
    ('PERMISSION_DELETE_COURSE'),
    ('PERMISSION_VIEW_COURSE'),
    ('PERMISSION_UPDATE_COURSE'),
    ('PERMISSION_CREATE_ROLE'),
    ('PERMISSION_EDIT_ROLE'),
    ('PERMISSION_DELETE_ROLE');
